import { Routes, Route } from 'react-router-dom';
import { AppLayout } from '../layouts/AppLayout';
import { DashboardPage } from '../features/dashboard/DashboardPage';
import { PlaceholderPage } from '../features/shared/PlaceholderPage';
import { ConfigurationPage } from '../features/settings/ConfigurationPage';
import { QuoteImportPage } from '../features/quote-import/QuoteImportPage';
import { ProtectedRoute } from '../auth/ProtectedRoute';
const modules: [string,string,string][] = [['imports','Historique des imports','Suivi des opérations d’import, statuts et erreurs.'],['dossiers','Dossiers SAV','Suivi des dossiers issus d’un devis validé et de leur historique.'],['scheduling','Planning atelier','Planification des tâches, techniciens et ressources.'],['workshop-control','Pilotage atelier','Vue opérationnelle des tâches et ordres de réparation.'],['techniciens','Techniciens','Compétences et disponibilité des techniciens.'],['equipes','Équipes','Équipes, horaires, absences et organisation atelier.'],['ressources','Ressources','Zones, ponts et disponibilités des ressources atelier.'],['quality-control','Contrôle qualité','Contrôles de sortie et reprises.'],['livraisons','Livraisons','Préparation et remise du dossier clôturé.'],['garantie','Garantie','Dossiers et décisions de garantie.'],['reclamations','Réclamations','Réclamations et résolution.'],['satisfaction','Satisfaction','Enquêtes et indicateurs de satisfaction.'],['rapports','Rapports','KPI, exports et tableaux de bord de pilotage.'],['utilisateurs','Utilisateurs','Utilisateurs, rôles et permissions.'],['settings','Paramètres','Paramétrage de l’organisation et des ateliers.'],['audit','Audit','Journal des événements et traçabilité.']];
export function AppRoutes() { return <Routes><Route element={<AppLayout/>}><Route path="/configuration" element={<ConfigurationPage/>}/><Route path="/" element={<ProtectedRoute><DashboardPage/></ProtectedRoute>}/><Route path="/quote-import" element={<ProtectedRoute><QuoteImportPage/></ProtectedRoute>}/>{modules.map(([path,title,description]) => <Route key={path} path={`/${path}`} element={<ProtectedRoute><PlaceholderPage title={title} description={description}/></ProtectedRoute>}/>)}</Route></Routes>; }
