import type { QuoteDelimiter, QuoteImportIssue, QuoteRawRow, QuoteRawSheet, QuoteSourceFile } from '../domain/types';

export type CsvParseResult = { sheet?: QuoteRawSheet; issues: QuoteImportIssue[] };
const issue = (code: QuoteImportIssue['code'], severity: QuoteImportIssue['severity'], message: string, extra: Partial<QuoteImportIssue> = {}): QuoteImportIssue => ({ code, severity, message, ...extra });
export function detectDelimiter(text: string): QuoteDelimiter | undefined { const first = text.replace(/^\uFEFF/, '').split(/\r?\n/, 1)[0] ?? ''; const comma = (first.match(/,/g) ?? []).length; const semicolon = (first.match(/;/g) ?? []).length; return comma === 0 && semicolon === 0 ? undefined : semicolon > comma ? ';' : ','; }
export function parseCsv(text: string, delimiter?: QuoteDelimiter): CsvParseResult {
  const clean = text.replace(/^\uFEFF/, ''); const chosen = delimiter ?? detectDelimiter(clean); if (!chosen) return { issues: [issue('HEADER_MISSING','BLOCKING','Aucun séparateur CSV détecté.')] };
  const records: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false; let line = 1; const issues: QuoteImportIssue[] = [];
  for (let i = 0; i < clean.length; i += 1) { const char = clean[i]; const next = clean[i + 1]; if (char === '"') { if (quoted && next === '"') { cell += '"'; i += 1; } else quoted = !quoted; continue; } if (char === chosen && !quoted) { row.push(cell); cell = ''; continue; } if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && next === '\n') i += 1; row.push(cell); if (row.some((value) => value.trim() !== '')) records.push(row); row = []; cell = ''; line += 1; continue; } cell += char; }
  if (quoted) issues.push(issue('INCONSISTENT_CONTENT','BLOCKING','Guillemet non fermé dans le fichier CSV.', { sourceRowNumber: line })); row.push(cell); if (row.some((value) => value.trim() !== '')) records.push(row);
  const headers = records.shift()?.map((header) => header.trim()) ?? []; if (!headers.length || headers.every((header) => !header)) issues.push(issue('HEADER_MISSING','BLOCKING','Le fichier ne contient pas d’en-têtes.'));
  const normalized = headers.map((header) => header.normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toLowerCase()); const duplicates = normalized.filter((header, index) => header && normalized.indexOf(header) !== index); for (const header of [...new Set(duplicates)]) issues.push(issue('DUPLICATE_HEADER','BLOCKING',`En-tête dupliqué : ${header}.`, { sourceColumn: header }));
  const rows: QuoteRawRow[] = records.map((values, index) => { const rowIssues: QuoteImportIssue[] = []; if (values.length !== headers.length) rowIssues.push(issue('INCONSISTENT_CONTENT','ERROR','Nombre de cellules différent du nombre d’en-têtes.', { sourceRowNumber: index + 2 })); for (const value of values) if (/^[=+@]/.test(value.trim())) rowIssues.push(issue('DANGEROUS_FORMULA','WARNING','Cellule potentiellement dangereuse détectée.', { sourceRowNumber: index + 2, sourceValue: value })); return { sourceRowNumber: index + 2, cells: headers.map((header, columnIndex) => ({ sourceValue: (values[columnIndex] ?? '').trim(), columnIndex, sourceColumn: header })), issues: rowIssues }; });
  const allIssues = [...issues, ...rows.flatMap((item) => item.issues)]; return { sheet: { headers, rows, delimiter: chosen, issues: allIssues }, issues: allIssues };
}
export function decodeUtf8(bytes: Uint8Array): { text?: string; valid: boolean } { try { return { text: new TextDecoder('utf-8', { fatal: true }).decode(bytes), valid: true }; } catch { return { valid: false }; } }
export function validateCsvSourceFile(file: QuoteSourceFile): { valid: boolean; issues: QuoteImportIssue[] } { const issues: QuoteImportIssue[] = []; if (!file || !file.name) issues.push(issue('FILE_MISSING','BLOCKING','Fichier absent.')); if (file.size === 0) issues.push(issue('FILE_EMPTY','BLOCKING','Le fichier est vide.')); if (file.size > 10 * 1024 * 1024) issues.push(issue('FILE_TOO_LARGE','BLOCKING','Le fichier dépasse 10 Mo.')); if (!/\.csv$/i.test(file.name)) issues.push(issue('EXTENSION_INVALID','BLOCKING','Seuls les fichiers CSV UTF-8 sont supportés.')); if (file.type && !['text/csv','application/csv',''].includes(file.type)) issues.push(issue('MIME_INVALID','WARNING','Le type MIME déclaré ne correspond pas exactement à text/csv.')); const decoded = decodeUtf8(file.bytes); if (!decoded.valid) issues.push(issue('ENCODING_INVALID','BLOCKING','Le fichier n’est pas encodé en UTF-8 valide.')); if (decoded.text !== undefined && decoded.text.length > 20_000_000) issues.push(issue('ROW_LIMIT_EXCEEDED','BLOCKING','Le contenu dépasse la limite autorisée.')); return { valid: issues.every((item) => item.severity !== 'BLOCKING'), issues };
}
export function sourceFileToText(file: QuoteSourceFile): string { return decodeUtf8(file.bytes).text ?? ''; }
