import type { NormalizationResult, OperationCategory, OperationCategorySuggestion, WorkshopStage, WorkshopStageSuggestion } from '../domain/types';
const result = <T>(sourceValue: string, normalizedValue: T | undefined, success: boolean, warnings: string[] = [], errors: string[] = [], confidenceScore?: number): NormalizationResult<T> => ({ sourceValue, normalizedValue, success, warnings, errors, confidenceScore });
export function trimUnicode(value: string): string { return value.replace(/^\uFEFF/, '').trim(); }
export function normalizeWhitespace(value: string): string { return trimUnicode(value).replace(/\s+/gu, ' '); }
export function normalizeHeader(value: string): string { return normalizeWhitespace(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, ''); }
export function normalizePhone(value: string): NormalizationResult<string> { const source = normalizeWhitespace(value); const normalized = source.replace(/[^\d+]/g, ''); return result<string>(value, normalized || undefined, Boolean(normalized), [], normalized ? [] : ['Téléphone vide.'], normalized ? 0.95 : 0.1); }
export function normalizeEmail(value: string): NormalizationResult<string> { const normalized = normalizeWhitespace(value).toLowerCase(); const valid = !normalized || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized); return result<string>(value, normalized || undefined, valid, [], valid ? [] : ['Adresse e-mail invalide.'], valid ? 0.98 : 0.1); }
export function normalizeRegistrationNumber(value: string): NormalizationResult<string> { const normalized = normalizeWhitespace(value).toUpperCase().replace(/[\s-]+/g, ''); return result<string>(value, normalized || undefined, Boolean(normalized), [], [], normalized ? 0.9 : 0.2); }
export function normalizeVin(value: string): NormalizationResult<string> { const normalized = normalizeWhitespace(value).toUpperCase().replace(/\s+/g, ''); const valid = !normalized || /^[A-HJ-NPR-Z0-9]{11,17}$/.test(normalized); return result<string>(value, normalized || undefined, valid, [], valid ? [] : ['VIN invalide.'], valid ? 0.95 : 0.1); }
export function parseLocalizedNumber(value: string): NormalizationResult<number> { const source = normalizeWhitespace(value).replace(/\u00a0/g, ''); if (!source) return result<number>(value, undefined, false, [], ['Nombre vide.'], 0); const lastComma = source.lastIndexOf(','); const lastDot = source.lastIndexOf('.'); let normalized = source.replace(/\s/g, ''); if (lastComma >= 0 && lastDot >= 0) normalized = lastComma > lastDot ? normalized.replace(/\./g, '').replace(',', '.') : normalized.replace(/,/g, ''); else if (lastComma >= 0) normalized = normalized.replace(',', '.'); const number = Number(normalized); return Number.isFinite(number) ? result<number>(value, number, true, [], [], 0.98) : result<number>(value, undefined, false, [], ['Nombre invalide.'], 0.1); }
export function parseLocalizedDate(value: string): NormalizationResult<string> { const source = normalizeWhitespace(value); if (!source) return result<string>(value, undefined, true, [], [], 0.5); const match = /^(\d{2})[/-](\d{2})[/-](\d{4})$/.exec(source); const iso = /^\d{4}-\d{2}-\d{2}$/.test(source) ? source : match ? `${match[3]}-${match[2]}-${match[1]}` : undefined; if (!iso) return result<string>(value, undefined, false, [], ['Date invalide.'], 0.1); const [year, month, day] = iso.split('-').map(Number); const date = new Date(Date.UTC(year, month - 1, day)); const valid = date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day; return valid ? result<string>(value, iso, true, [], [], 0.98) : result<string>(value, undefined, false, [], ['Date invalide.'], 0.1); }
export function normalizeCurrency(value: string): NormalizationResult<string> { const normalized = normalizeWhitespace(value).toUpperCase(); const currency = normalized === 'DT' || normalized === 'TND' ? 'TND' : normalized || 'TND'; return result(value, currency, true, normalized ? [] : ['Devise absente, TND utilisé par défaut.'], [], normalized ? 0.95 : 0.5); }
export function normalizeQuoteLabel(value: string): NormalizationResult<string> { const normalized = normalizeWhitespace(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); return result(value, normalized, Boolean(normalized), [], normalized ? [] : ['Libellé vide.'], normalized ? 0.95 : 0.05); }
export function normalizeUnit(value: string): NormalizationResult<string> { const normalized = normalizeWhitespace(value).toLowerCase(); return result(value, normalized || 'unit', true, normalized ? [] : ['Unité absente, unit utilisé.'], [], normalized ? 0.9 : 0.5); }
export function normalizeOperationCategory(value: string): OperationCategorySuggestion { const text = normalizeWhitespace(value).toLowerCase(); const rules: [OperationCategory, string[]][] = [['PAINT',['peinture','vernissage','vernis']],['BODYWORK',['tolerie','carrosserie','dressage','debosselage']],['MECHANICAL',['mecanique','vidange','frein','moteur','geometrie']],['ELECTRICAL',['electrique','batterie','faisceau','diagnostic']],['DIAGNOSTIC',['diagnostic','controle']],['MATERIAL',['fourniture','consommable','produit','matiere']]]; const found = rules.find(([, keys]) => keys.some((key) => text.includes(key))); return { category: found?.[0] ?? 'LABOR', confidenceScore: found ? 0.82 : 0.55, rule: found ? 'keyword' : 'default-labor', detectedKeywords: found ? found[1].filter((key) => text.includes(key)) : [], warning: found ? undefined : 'Catégorie proposée par défaut, correction manuelle recommandée.' }; }
export function normalizeWorkshopStage(value: string): WorkshopStageSuggestion { const text = normalizeWhitespace(value).toLowerCase(); const rules: [WorkshopStage, string[]][] = [['QUALITY_CONTROL',['controle qualite','qualite']],['PREPARATION',['preparation','appret','d_p']],['PRIMER',['appret']],['PAINT_APPLICATION',['peinture','application']],['VARNISH',['vernis','finition']],['DRYING',['sechage']],['BODY_REPAIR',['dressage','carrosserie','tolerie']],['DISASSEMBLY',['depose','demontage']],['REASSEMBLY',['repose','remontage']],['MECHANICAL_REPAIR',['mecanique','vidange','frein']],['ELECTRICAL_REPAIR',['electrique','faisceau','batterie']],['DIAGNOSTIC',['diagnostic']]]; const found = rules.find(([, keys]) => keys.some((key) => text.includes(key))); return { stage: found?.[0] ?? 'UNSPECIFIED', confidenceScore: found ? 0.82 : 0.45, rule: found ? 'keyword' : 'unspecified', detectedKeywords: found ? found[1].filter((key) => text.includes(key)) : [], warning: found ? undefined : 'Étape non reconnue, correction manuelle requise.', manualCorrectionAllowed: true }; }
