import { useState } from 'react';
import { NavLink, Outlet } from 'react-router-dom';
import { Menu, X, ShieldCheck, ChevronDown } from 'lucide-react';
import { useAuth } from '../auth/AuthProvider';
import { hasPermission, type Permission } from '../types/auth';
export const NAV_ITEMS: { label: string; path: string; permission: Permission }[] = [
  ['Tableau de bord','/','dashboard.read'], ['Importer un devis','/quote-import','quote-import.manage'], ['Historique des imports','/imports','imports.read'], ['Dossiers','/dossiers','cases.read'], ['Planning atelier','/scheduling','workshop.plan'], ['Pilotage atelier','/workshop-control','workshop.execute'], ['Techniciens','/techniciens','technicians.manage'], ['Équipes','/equipes','teams.manage'], ['Ressources','/ressources','resources.manage'], ['Contrôle qualité','/quality-control','quality.manage'], ['Livraisons','/livraisons','delivery.manage'], ['Garantie','/garantie','warranty.manage'], ['Réclamations','/reclamations','complaints.manage'], ['Satisfaction','/satisfaction','satisfaction.read'], ['Rapports','/rapports','reports.read'], ['Utilisateurs','/utilisateurs','users.manage'], ['Paramètres','/settings','settings.manage'], ['Audit','/audit','audit.read']
].map(([label,path,permission]) => ({ label, path, permission: permission as Permission }));
export function AppLayout() { const [open, setOpen] = useState(false); const { user } = useAuth(); const roles = user?.roles ?? []; return <div className="min-h-screen bg-mist text-slate-800"><aside className={`fixed inset-y-0 left-0 z-30 w-72 transform bg-ink p-5 text-white transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between"><div><div className="text-xl font-bold tracking-tight">NIMR <span className="text-teal">SAV PRO</span></div><p className="mt-1 text-xs text-slate-300">Service Après-Vente · V2</p></div><button className="lg:hidden" onClick={() => setOpen(false)} aria-label="Fermer le menu"><X size={20}/></button></div><nav className="mt-8 space-y-1" aria-label="Navigation principale">{NAV_ITEMS.filter((item) => hasPermission(roles, item.permission)).map((item) => <NavLink key={item.path} to={item.path} onClick={() => setOpen(false)} className={({isActive}) => `nav-item ${isActive ? 'nav-item-active' : ''}`}>{item.label}</NavLink>)}</nav><div className="absolute bottom-5 left-5 right-5 rounded-lg border border-white/10 bg-white/5 p-3 text-xs text-slate-300"><ShieldCheck size={16} className="mb-2 text-teal"/><p>Accès sécurisé par rôle</p><p className="mt-1 text-slate-400">Aucune session active</p></div></aside><div className="lg:pl-72"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-line bg-white/90 px-4 backdrop-blur md:px-8"><button className="rounded-lg p-2 hover:bg-mist lg:hidden" onClick={() => setOpen(true)} aria-label="Ouvrir le menu"><Menu/></button><div className="hidden text-sm text-slate-500 sm:block">Centre de pilotage SAV</div><div className="flex items-center gap-3 text-sm"><span className="hidden text-right sm:block"><strong className="block text-ink">Non connecté</strong><span className="text-xs text-slate-500">Configuration requise</span></span><ChevronDown size={16} className="text-slate-400"/></div></header><main className="mx-auto max-w-[1600px] p-4 md:p-8"><Outlet /></main></div>{open && <button className="fixed inset-0 z-20 bg-ink/40 lg:hidden" onClick={() => setOpen(false)} aria-label="Fermer le menu"/>}</div>; }
